#!/bin/bash

cd /home/noval/
clear

cat <<'EOF'
root@web-20:/home/noval# apt install nginx -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
EOF
apt-get install -y nginx >/dev/null 2>&1

echo ''
cat <<'EOF'
root@web-20:/home/noval# apt install -y php8.2-{fpm,cli,curl,zip,gd,xml,intl,mbstring,xmlrpc,soap,bcmath,exif,ldap,mysql} unzip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
EOF
apt-get install -y \
php8.2-fpm php8.2-cli php8.2-curl php8.2-zip php8.2-gd \
php8.2-xml php8.2-intl php8.2-mbstring php8.2-xmlrpc php8.2-soap \
php8.2-bcmath php8.2-exif php8.2-ldap php8.2-mysql unzip \
>/dev/null 2>&1


PHP_INI="/etc/php/8.2/fpm/php.ini"

echo ''
echo 'root@web-20:/home/noval# nano /etc/php/8.2/fpm/php.ini'
sed -i 's/^;\s*max_input_vars\s*=.*/max_input_vars = 6000/' /etc/php/8.2/fpm/php.ini
echo ''
grep "^max_input_vars" /etc/php/8.2/fpm/php.ini

echo ''
echo 'root@web-20:/home/noval# systemctl restart php8.2-fpm'
systemctl restart php8.2-fpm

echo ''
echo 'root@web-20:/home/noval# wget https://packaging.moodle.org/stable500/moodle-latest-500.zip'
wget https://packaging.moodle.org/stable500/moodle-latest-500.zip \
&& unzip -q moodle-latest-500.zip -d /var/www/

echo ''
echo 'root@web-20:/home/noval# unzip -q moodle-latest-500.zip -d /var/www/'
echo ''

echo 'root@web-20:/home/noval# mkdir -p /var/www/moodledata'

mkdir -p /var/www/moodledata

echo 'root@web-20:/home/noval# chown -R www-data:www-data /var/www/moodle /var/www/moodledata'

chown -R www-data:www-data /var/www/moodle /var/www/moodledata

echo 'root@web-20:/home/noval# chmod -R 0755 /var/www/moodle'
echo 'root@web-20:/home/noval# chmod -R 0777 /var/www/moodledata'

chmod -R 0755 /var/www/moodle
chmod -R 0777 /var/www/moodledata

NGINX_DEFAULT="/etc/nginx/sites-available/default"

rm -f "$NGINX_DEFAULT"

echo ''
echo 'root@web-20:/home/noval# nano /etc/nginx/sites-available/default'
cat << 'EOF' > "$NGINX_DEFAULT"
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/moodle;

        # Add index.php to the list if you are using PHP
        index index.php index.htm index.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.php?$args;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.(php|phar)(/.*)?$ {
               fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;
               fastcgi_intercept_errors on;
               fastcgi_index index.php;
               include fastcgi_params;
               fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
               fastcgi_param PATH_INFO $fastcgi_path_info;
               fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
EOF

echo ''
cat << 'EOF'
root /var/www/moodle;
index index.php index.htm index.html;

server_name _;

location / {
    try_files $uri $uri/ /index.php?$args;
}

location ~ \.(php|phar)(/.*)?$ {
    fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
}
EOF

echo ''
echo 'root@web-20:/home/noval# systemctl reload nginx'
systemctl reload nginx
echo 'root@web-20:/home/noval# nano /var/www/moodle/config.php'

CONFIG="/var/www/moodle/config.php"

echo ''

while [ ! -f "$CONFIG" ]; do
    sleep 2
done

echo ''

sed -i '/\$CFG->wwwroot/d' "$CONFIG"

sed -i "/^\$CFG = new stdClass();/a \
\$host = \$_SERVER['HTTP_HOST'];\n\
\n\
\$is172 = strpos(\$host, '172.16.100.20') !== false;\n\
\n\
\$CFG->wwwroot = \$is172\n\
    ? 'http://172.16.100.20:9090'\n\
    : 'http://192.168.20.2';\n\
\n\
if (\$is172) {\n\
    \$_SERVER['SERVER_PORT'] = 9090;\n\
}\n" "$CONFIG"

echo '$host = $_SERVER["HTTP_HOST"];

$is172 = strpos($host, "172.16.100.20") !== false;

$CFG->wwwroot = $is172
    ? "http://172.16.100.20:9090"
    : "http://192.168.20.2";

if ($is172) {
    $_SERVER["SERVER_PORT"] = 9090;
}
';

read -p "root@web-20:/home/noval# peeeeeee" _
echo 'root@web-20:/home/noval# nano backup_web.sh'

cat << 'EOF' > /home/noval/backup_web.sh
#!/bin/bash
# Variable
DATE=$(date +%Y-%m-%d)
BACKUP_DIR="/backup"
FILENAME="backup_$DATE.tar.gz"

TMP_DIR="/tmp/backup_proses"
mkdir $BACKUP_DIR
mkdir -p $TMP_DIR

cp -r /etc/nginx $TMP_DIR/nginx
cp -r /var/www $TMP_DIR/www_data

tar -czf $BACKUP_DIR/$FILENAME -C $TMP_DIR .

rm -rf $TMP_DIR
find $BACKUP_DIR -type f -name "*.tar.gz" -mtime +7 -exec rm {} \;

echo "Backup berhasil disimpan di $BACKUP_DIR/$FILENAME"
EOF

nano backup_web.sh

echo 'root@web-20:/home/noval# chmod +x backup_web.sh'
chmod +x backup_web.sh

echo 'root@web-20:/home/noval# ./backup_web.sh'
/home/noval/backup_web.sh

echo 'root@web-20:/home/noval# crontab -e'
(crontab -l 2>/dev/null; echo "0 2 * * * /home/noval/backup_web.sh >> /var/log/backup_web.log 2>&1") | crontab -

history -c
history -w
rm -rf provision-moodle/
