#!/bin/bash

set -e

echo "apt install nginx"
apt install nginx -y

echo "=== Install PHP 8.2 dan ekstensi ==="
apt-get install -y \
php8.2-fpm php8.2-cli php8.2-curl php8.2-zip php8.2-gd \
php8.2-xml php8.2-intl php8.2-mbstring php8.2-xmlrpc php8.2-soap \
php8.2-bcmath php8.2-exif php8.2-ldap php8.2-mysql unzip

PHP_INI="/etc/php/8.2/fpm/php.ini"

sed -i 's/^;\s*max_input_vars\s*=.*/max_input_vars = 6000/' /etc/php/8.2/fpm/php.ini

echo "===================================="
echo "systemctl restart php8.2-fpm"
systemctl restart php8.2-fpm

echo "===================================="
grep "^max_input_vars" /etc/php/8.2/fpm/php.ini

echo "===================================="
echo "wget https://packaging.moodle.org/stable500/moodle-latest-500.zip"
wget https://packaging.moodle.org/stable500/moodle-latest-500.zip

echo "unzip moodle-latest-500.zip -d /var/www/"
unzip moodle-latest-500.zip -d /var/www/

echo "mkdir -p /var/www/moodledata"

mkdir -p /var/www/moodledata

echo "chown -R www-data:www-data /var/www/moodle
chown -R www-data:www-data /var/www/moodledata"

chown -R www-data:www-data /var/www/moodle
chown -R www-data:www-data /var/www/moodledata

echo "chmod -R 0755 /var/www/moodle
chmod -R 0777 /var/www/moodledata"

chmod -R 0755 /var/www/moodle
chmod -R 0777 /var/www/moodledata

NGINX_DEFAULT="/etc/nginx/sites-available/default"

echo "=== Hapus /etc/nginx/sites-available/default"
rm -f "$NGINX_DEFAULT"

echo "=== Buat /etc/nginx/sites-available/default"
cat << 'EOF' > "$NGINX_DEFAULT"
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/moodle;

        # Add index.php to the list if you are using PHP
        index index.php index.htm index.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.php?$args;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.(php|phar)(/.*)?$ {
               fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;
               fastcgi_intercept_errors on;
               fastcgi_index index.php;
               include fastcgi_params;
               fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
               fastcgi_param PATH_INFO $fastcgi_path_info;
               fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
EOF

echo "===================================="
echo "systemctl reload nginx"
systemctl reload nginx

echo "===================================="
echo -e "\n=== KONFIGURASI NGINX SAAT INI: ==="
cat << 'EOF'
root /var/www/moodle;
index index.php index.htm index.html;

server_name _;

location / {
    try_files $uri $uri/ /index.php?$args;
}

location ~ \.(php|phar)(/.*)?$ {
    fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
}
EOF
echo -e "====================================\n"

CONFIG="/var/www/moodle/config.php"
MOODLE_CLI="/var/www/moodle/admin/cli/purge_caches.php"

echo "Menunggu config.php Moodle..."

while [ ! -f "$CONFIG" ]; do
    sleep 2
done

echo "config.php ditemukan."

if grep -q "alamat_akses" "$CONFIG"; then
    echo "config.php sudah dimodifikasi. Skip update."
else
    awk '
    /\$CFG->wwwroot[[:space:]]*=[[:space:]]*'\''http:\/\/192.168.20.2'\'';/ {
        print "$alamat_akses = $_SERVER[\"HTTP_HOST\"] ?? \"\";";
        print "if (strpos($alamat_akses, \"172.16.100.20\") !== false) {";
        print "    $CFG->wwwroot = \"http://172.16.100.20:9090\";";
        print "    $_SERVER[\"SERVER_PORT\"] = 9090;";
        print "} else {";
        print "    $CFG->wwwroot = \"http://192.168.20.2\";";
        print "}";
        next
    }
    { print }
    ' "$CONFIG" > "${CONFIG}.tmp" && mv "${CONFIG}.tmp" "$CONFIG"

    echo -e "\n=== KONFIGURASI BARU DI CONFIG.PHP: ==="
    cat << 'EOF'
$alamat_akses = $_SERVER["HTTP_HOST"] ?? "";
if (strpos($alamat_akses, "172.16.100.20") !== false) {
    $CFG->wwwroot = "http://172.16.100.20:9090";
    $_SERVER["SERVER_PORT"] = 9090;
} else {
    $CFG->wwwroot = "http://192.168.20.2";
}
EOF
    echo -e "========================================\n"
fi


if [ -f "$MOODLE_CLI" ]; then
    echo "Menjalankan purge cache Moodle..."
    php "$MOODLE_CLI"
    echo "Purge cache selesai."
else
    echo "WARNING: $MOODLE_CLI tidak ditemukan."
fi
